[package]
name = "openvr"
version = "0.4.0"
authors = [
    "Colin Sherratt",
    "Erick Tryzelaar",
    "Rene Eichhorn",
    "Benjamin Saunders"
]
license-file = "LICENSE.md"

documentation = "http://rust-openvr.github.io/rust-openvr/openvr/index.html"
homepage = "https://github.com/rust-openvr/rust-openvr"
repository = "https://github.com/rust-openvr/rust-openvr"

description = "A safe binding for openvr."

[dependencies]
openvr_sys = { git = "https://github.com/Ralith/rust-openvr-sys.git" }
lazy_static = "0.2.8"

[dev_dependencies]
glium = "0.14.0"
nalgebra = "0.12"
